import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Blog Application</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className="text-6xl font-bold underline text-primary-dark">Hello world!</h1>
      </main>
    </div>
  );
}
